// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes blink rate, yawn rate, Eye Aspect Ratio (EAR), and Mouth Aspect Ratio (MAR) to estimate drowsiness level.
 *
 * - drowsinessAnalysis - A function that handles the drowsiness analysis process.
 * - DrowsinessAnalysisInput - The input type for the drowsinessAnalysis function.
 * - DrowsinessAnalysisOutput - The return type for the drowsinessAnalysis function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DrowsinessAnalysisInputSchema = z.object({
  blinkRate: z.number().describe('The number of blinks per minute.'),
  yawnRate: z.number().describe('The number of yawns per minute.'),
  eyeAspectRatio: z.number().describe('The calculated Eye Aspect Ratio (EAR).'),
  mouthAspectRatio: z.number().describe('The calculated Mouth Aspect Ratio (MAR).'),
  confoundingCircumstances: z
    .string()
    .optional()
    .describe(
      'Any confounding circumstances that might affect the interpretation of the metrics (e.g., allergies, dry eyes, talking).'
    ),
});
export type DrowsinessAnalysisInput = z.infer<typeof DrowsinessAnalysisInputSchema>;

const DrowsinessAnalysisOutputSchema = z.object({
  drowsinessLevel: z
    .string()
    .describe(
      'An estimation of the drowsiness level, based on the input metrics and any confounding circumstances. Possible values: Alert, Slightly Drowsy, Moderately Drowsy, Severely Drowsy.'
    ),
  confidence: z
    .number()
    .describe('A confidence score (0-1) indicating the certainty of the drowsiness level estimation.'),
  rationale: z
    .string()
    .describe(
      'Explanation of why the LLM assigned the current drowsiness level, taking into account the inputs, thresholds, and any confounding circumstances.'
    ),
});
export type DrowsinessAnalysisOutput = z.infer<typeof DrowsinessAnalysisOutputSchema>;

export async function drowsinessAnalysis(input: DrowsinessAnalysisInput): Promise<DrowsinessAnalysisOutput> {
  return drowsinessAnalysisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'drowsinessAnalysisPrompt',
  input: {schema: DrowsinessAnalysisInputSchema},
  output: {schema: DrowsinessAnalysisOutputSchema},
  prompt: `You are an expert in analyzing drowsiness levels based on several metrics.

  Given the following metrics, estimate the drowsiness level of the person:

  Blink Rate: {{blinkRate}} blinks/minute
  Yawn Rate: {{yawnRate}} yawns/minute
  Eye Aspect Ratio (EAR): {{eyeAspectRatio}}
  Mouth Aspect Ratio (MAR): {{mouthAspectRatio}}

  Consider these general guidelines, but adapt as necessary:

  - **Alert:** Normal blink rate, low yawn rate, normal EAR and MAR.
  - **Slightly Drowsy:** Slightly reduced blink rate, slightly increased yawn rate, slightly lower EAR and higher MAR.
  - **Moderately Drowsy:** Reduced blink rate, increased yawn rate, lower EAR and higher MAR.
  - **Severely Drowsy:** Significantly reduced blink rate, very high yawn rate, very low EAR and very high MAR.

  Also, take into account any confounding circumstances that could affect the metrics:

  Confounding Circumstances: {{#if confoundingCircumstances}}{{confoundingCircumstances}}{{else}}None{{/if}}

  Given all of the above information, estimate the drowsiness level, and provide a confidence score (0-1) for your estimation and a rationale.

  Drowsiness Level: { {{drowsinessLevel}} }
  Confidence: { {{confidence}} }
  Rationale: { {{rationale}} }`,
});

const drowsinessAnalysisFlow = ai.defineFlow(
  {
    name: 'drowsinessAnalysisFlow',
    inputSchema: DrowsinessAnalysisInputSchema,
    outputSchema: DrowsinessAnalysisOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
